[green_agent]
endpoint = "http://127.0.0.1:9009"
cmd = "python scenarios/design2code/design2code_evaluator.py --host 127.0.0.1 --port 9009"

[[participants]]
role = "agent"
endpoint = "http://127.0.0.1:9019"
cmd = "python scenarios/design2code/design2code_agent.py --host 127.0.0.1 --port 9019"

[config]
dataset_name = "SALT-NLP/Design2Code-hf"
num_tasks = 5
